"""import random
list1 = [1,23,43,657,856,35644,345]
a = random.choice(list1)
print(a)
random.shuffle(list1)
print(list1)
b = random.randint(1,100)
print(b)
c = random.randrange(1,3)
print(c)
a = random.random()
print(a)
a = random.uniform(1,3)
print(a)
text = "Welcome to India"
text_splitted = text.split()
print(text_splitted)
text_splited = text.split("e")
print(text_splited)
names = input("Enter the names separated by coma:")
names_list = names.split(",")
#print(names_list)
length = len(names_list)
random_choice = random.randint(0,length-1)
print(f"{names_list[random_choice]} will pay the bill.")
name = input ("Enter everybody names separated by comma:")
name_list= name.split(",")
person_selected = random.choice(name_list)
print(f"{person_selected} will pay the bill.")
name = input ("Enter everybody names separated by comma:")
name_list= name.split(",")
print(f"{random.choice(name_list)} will pay the bill.")"""
num = [1,32,23,212,132,[2937,847,8174],8264,82.214]
length = len(num)
print(length)
print(num)
print(num[5])
print(num[5][0])
print(num[5][1])
print(num[-2])
print(num[-3])
print(num[len(num)-1])
print(num[len(num)-3])
print(num[5][0:1])
print(num[5][0:3])
print(num[5][::])
print(num[5][::2])
list2 = [10,24,536,678,['Mohan','Shyam','Ram'],835,56,367]
print(list2)
print(list2[4])
print(list2[4][::])
print(list2[4][-2])
print(list2[4][:-1])
print(list2[4][-1])
print(list2[4][0])
print(list2[4][::3])
print(list2[4][0:3])
print(list2[4][-3:])
print(list2[4][0:2])