numbers = [10,0,-1,7,8]
print(numbers)
mix_list = [23,"Thanooj",True,1.7]
print(mix_list)
print(numbers[1])
print(numbers[-3])
print(numbers[-1])
print(len(numbers))
print(numbers[-5])
print(numbers[1:4])
print(numbers[:4])
print(numbers[0:])
print(numbers[:])
print(numbers[1:5])
print(numbers[0:5:1])
print(numbers[0:5:2])
print(numbers[0:5:3])
mix_list = [23,"Thanooj",True,1.7]
print(mix_list[0:4])
print(mix_list[0:4:1])
print(mix_list[0:4:2])
print(mix_list[0:4:3])
numbers = [23,3,56,-21,10.6,53,-46]
numbers.sort()
print(numbers)
numbers.reverse()
print(numbers)
mix_list.reverse()
print(mix_list)
print(min(numbers))
print(max(numbers))
numbers.append(45)
print(numbers)
mix_list.append(45)
print(mix_list)
numbers.insert(18,7)
print(numbers)
mix_list.insert(23,25)
print(mix_list)
numbers.extend([34,12,31,33,53,75,567])
print(numbers)
mix_list.extend([324,234,56,3765,325])
print(mix_list)
numbers[0]= 1
print(numbers)
mix_list[0]=1
print(mix_list)
numbers[1:4]= [24,35,57]
print(numbers)
mix_list[4:7]= [24,35,57]
print(mix_list)
numbers = [10,0,-1,7,8]
print(numbers.count(0))
print(numbers.count(-1))
print(numbers.count(2))
numbers.remove(7)
print(numbers)
numbers.pop(1)
print(numbers)
print(numbers.count(10))
numbers.pop(1)
print(numbers)
numbers.index(8)
print(numbers)
numbers.clear()
print(numbers)
numbers = [100,200,300,400,500,600]
numbers.index(300)
print(numbers)
print(numbers.index(300))
import random
t = [32,4,235,2123,-34,24,-23]
a = random.choice(t)
print(a)
import random

a =random.randint(1,100)
print(a)
a = random.randint(1,50)
print(a)
a = random.randrange(1,4)
print(a)
a = random.random()
print(a)
a = random.uniform(0,3)
print(a)
import random
side = random.randint(0,1)
if side == 1:
    print("heads")
else:
    print("tails")
text = "Welcome to India"
text_split= text.split(" ")
print(text_split)
text = "Welcome to india"
splitted_text =  text.split("e")
print(splitted_text)
import random
names = input("Enter everybody names separated by comma:")
name_list = names.split(",")
length = len(name_list)
random_choice =random.randint(0,length-1)
print(f"{name_list[random_choice]} will pay the bill.")
import random
names = input("Enter everybody names separated by comma:")
name_list = names.split(",")
person_selected = random.choice(name_list)
print(f"{person_selected} will pay the bill.")
import random
names = input("Enter everybody names separated by comma:")
name_list = names.split(",")
print(f"{random.choice(name_list)} will pay the bill.")
numbers = [10,20,30,40,[25,34,56,65],50,60]
print(numbers)
print(len(numbers))
print(numbers[5])
print(numbers[4])
print(numbers[4][0])
print(numbers[4][1])
print(numbers[4][3])
print(numbers[-2])
print(numbers[4][0:4])
print(numbers[4][:])
print(numbers[4][::])
print(numbers[4][0::2])
print(numbers[4][0::3])
