numbers = [10,0,-1,7,8,10]
print(numbers)
mix_list = [1,'Thanooj',True,10.10]
print(mix_list)
print(numbers[1])
print(numbers[2])
print(numbers[-1])
print(numbers[-2])
print(numbers[0:4])
print(numbers[::2])
print(numbers[::-1])
print(numbers[1:4])
print(numbers[1:3])
print(numbers[0:5:1])
print(numbers[0:5:2])
print(numbers[0:5:3])
names = ['Thanooj','Krishna','Ram']
print(names)
print(names[0])
numbers.sort()
print(numbers)
numbers.reverse()
print(numbers)
print(min(numbers))
print(max(numbers))
numbers.append(10)
print(numbers)
numbers.insert(1,'Thanooj')
print(numbers)
numbers.remove('Thanooj')
print(numbers)
numbers.extend(['Thanooj','Krishna','Ram'])
print(numbers)
numbers[1] = 45
print(numbers)
numbers[1:4] = [45,46,47]
print(numbers)
numbers.pop()
print(numbers)
print(numbers.count(10))
print(numbers.index(10))
numbers.remove(10)
print(numbers)